@startuml




Impl o--> protos.StreamStub
Impl o--> handlerMap
Impl *--> Engine
Peer <|-- Impl
Neighbour <|-- Impl

protos.StreamStub *--> protos.shandlerMap
protos.StreamStub *--> protos.StreamHandlerFactory
protos.shandlerMap *--> protos.StreamHandler

Handler *--> ChatStream
Handler o--> Impl
Handler --|> MessageHandler
Handler o--> ledger.Ledger



protos.StreamHandlerImpl <|.. statesync.stateSyncHandler
statesync.stateSyncHandler *--> statesync.syncer
statesync.stateSyncHandler ..> protos.StreamStub
statesync.stateSyncHandler *--> statesync.stateServer
protos.StreamHandler *--> protos.StreamHandlerImpl


stub.SyncFactory ..|> protos.StreamHandlerFactory


interface protos.StreamHandlerImpl  {
	Tag() string
	EnableLoss() bool
	NewMessage() proto.Message
	HandleMessage(proto.Message) error
	BeforeSendMessage(proto.Message) error
	OnWriteError(error)
	Stop()
}

class protos.StreamHandler  {
	SendMessage(m proto.Message) error
	GetName() string
}

class statesync.stateSyncHandler  {
	Tag() string
	EnableLoss() bool
	NewMessage() proto.Message
	HandleMessage(proto.Message) error
	BeforeSendMessage(proto.Message) error
	OnWriteError(error)
	Stop()
}



@enduml


、



interface BlocksRetriever  {
	RequestBlocks(*pb.SyncBlockRange) (<-chan *pb.SyncBlocks, error)
}

interface StateRetriever  {
	RequestStateSnapshot() (<-chan *pb.SyncStateSnapshot, error)
	RequestStateDeltas(syncBlockRange *pb.SyncBlockRange)
}

Handler o--> ledger.Ledger

BlocksRetriever <|-- RemoteLedger
StateRetriever <|-- RemoteLedger

Handler o--> syncStateSnapshotRequestHandler
Handler o--> syncStateDeltasHandler
Handler o--> syncBlocksRequestHandler