@startuml
[*] --> set_primary

set_primary->pow_submission
pow_submission-->ds_consensus_start

ds_consensus_done->mircoblock_submission

ds_consensus_start-->announce_done
finalblock_consensus_start-->announce_done
viewchange_consensus_start-->announce_done


announce_done-->commit_collection
ds_consensus_start-->commit_collection
finalblock_consensus_start-->commit_collection

commit_collection_done --> challenge_done

challenge_done --> response_collection



response_collection_done --> collectivesig_done
collectivesig_done --> finalcommit_collection

finalcommit_collection_done --> finalchallenge_done

finalchallenge_done --> finalresponse_collection

finalresponse_collection_done --> ds_consensus_done
finalresponse_collection_done --> finalblock_consensus_done
finalresponse_collection_done --> viewchange_consensus_done

@enduml