BIN_NAME=evaiod
COSMOS_TOP=${GOPATH}/src/github.com/cosmos/gaia
COSMOS_BIN=${GOPATH}/bin
COSMOS_NET_TOP=`pwd`
COSMOS_NET_CACHE=${COSMOS_NET_TOP}/cache

BASE_PORT_PREFIX=10000
P2P_PORT_SUFFIX=56

((RPC_PORT_SUFFIX    = 1 + P2P_PORT_SUFFIX))
((REST_PORT_SUFFIX   = 3 + P2P_PORT_SUFFIX))

((BASE_PORT    = BASE_PORT_PREFIX + P2P_PORT_SUFFIX))
((seedp2pport  = BASE_PORT_PREFIX + P2P_PORT_SUFFIX))
((seedrpcport  = BASE_PORT_PREFIX + RPC_PORT_SUFFIX))
((seedrestport = BASE_PORT_PREFIX + REST_PORT_SUFFIX))

