@startuml
[*] --> start_pow

start_pow->process_dsblock


mircoblock_consensus_done->process_finalblock
   mircoblock_consensus_prepare->announce_done
   viewchange_consensus_prepare->announce_done
   announce_done->commit_send


commit_send->challenge_done

challenge_done->response_send

response_send->collectivesig_done

collectivesig_done->finalcommit_send

finalcommit_send->finalchallenge_done
finalchallenge_done->finalresponse_send

finalresponse_send->mircoblock_consensus_done
finalresponse_send->viewchange_consensus_done


@enduml