@startuml

[*] --> synchandshake
synchandshake --> synclocating
synclocating --> syncdelta
synclocating --> syncsnapshot
synclocating --> syncblock


syncdelta --> [*]
syncsnapshot --> [*]
syncblock --> [*]

@enduml